### ISSUE TITLE
 scene graph generation using gt segmentaion

### ISSUE THREAD

**Issue by zzha5029** [ShunChengWu/3DSSG#12]
In 3DSSG/data_processing/gen_data_gt.py for scene graph generation using gt segmentaion
In line 299 target_relationships = ['supported by', 'attached to','standing on','hanging on','connected to','part of','build in'] 
According to your paper, it should have 26 different relationships, following the **relationships.txt** . It that correct?
In addition, is **none** included in target_relationships ?
Look forward to your reply.

**Comment by ShunChengWu** [comment]
The script we provided is mainly for reproducing the experiments we did after Table 1 in our paper. If you want to compare to the baseline method with the same classes and relationships. You will need to use the original data splits provided by the author of 3DSSG paper. 
In order to have a faired comparison to the previous method, using the exact same data and split is essential.

**Comment by zzha5029** [comment]
Thank you for your reply. I still want to know if **none** label included in target_relationships in the  line 299 of 3DSSG/data_processing/gen_data_gt.py?

**Comment by ShunChengWu** [comment]
No. The none relationship is added in runtime base on the configuration. Because previously we also tested on the multiple relationship prediction. In that case, whether a relationship exists or not is base on per-relationship prediction, i.e. >0.5.  You can check the data loader.  You can check here
https://github.com/ShunChengWu/3DSSG/blob/master/src/dataset_SGFN.py#L179

**Comment by zzha5029** [comment]
Thanks for your reply.

**Comment by zzha5029** [comment]
Thank you for your reply.
