### ISSUE TITLE
references.txt

### ISSUE THREAD

**Issue by yzthhjq** [ShunChengWu/3DSSG#29]
There is no references.txt in the folder

**Comment by ShunChengWu** [comment]
please run this
https://github.com/ShunChengWu/3DSSG/blob/master/README.md#preparation

**Comment by cbyan1003** [comment]
when i run `bash preparation.sh`, i met ERROR 404: Not Found.
so, i still can not get references.txt

**Comment by ShunChengWu** [comment]
it was the https issue. should be fixed. 
also, please put the full error message otherwise, it's not informative.

**Comment by cbyan1003** [comment]
sorry, I found that I can download the file from the linked network disk instead of `bash preparation.sh`.
also, I want to know that the required 3RScan dataset is just given in readme 
`python download.py -o /path/to/3RScan/ --type semseg.v2.json`
`python download.py -o /path/to/3RScan/ --type labels.instances.annotated.v2.ply`
or do I need to download the complete dataset?

**Comment by ShunChengWu** [comment]
If I remember correctly, those two should be enough.

**Comment by ShunChengWu** [comment]
closed due to inactivity
