### ISSUE TITLE
problem about running "python main.py --mode trace --config ./CVPR21/config_CVPR21.json"

### ISSUE THREAD

**Issue by admiral-chen** [ShunChengWu/3DSSG#31]
Dear author, 

When trying to run Trace mode with the provided CVPR21 model files, an error pop up saying "
  File "D:\SRC\3DSSG\./src\dataset_SGFN.py", line 144, in __init__
    with open(os.path.join(self.root[0],'args.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/sc/research/PersistentSLAM/python/3DSSG/data/3RScan_ScanNet20_InSeg_Full_20210430/args.json". 

By checking the config_CVPR21.json file, I found the path is actually the "dataset/root" variable in it. I wonder how to get the "args.json" file to run the code, and what files else should be present in the "3RScan_ScanNet20_InSeg_Full_20210430" folder .  

Looking forward to your reply~ Many thanks!

Best regards,
Yifei Chen

**Comment by admiral-chen** [comment]
Could anyone give some hint or help? I really don't know what the file "args.json" is. I have prepared datasets according to "Data preparation" here (https://github.com/ShunChengWu/3DSSG/tree/master/data_processing). However, there is no args.json file in any case.

Many thanks!

Yifei

**Comment by ShunChengWu** [comment]
I recall that those files are generated if you run the data_processing from scratch. 
It's hard to provide the generated data since the InSeg reconstruction returns a bit of a different segmentation outcome. We also cannot provide the output ply file since it inherits the license from 3DSSG.
We, therefore, didn't provide any pre-generated data. 

If you want to use the traced model, you can find it in the SceneGraphFusion [repo](https://github.com/ShunChengWu/SceneGraphFusion) or this [link](https://drive.google.com/file/d/1_745ofaOUyP_iFK8A3cSW60L4V7TlWa7/view).

**Comment by Landerku** [comment]
Hi, I believe the file you mentioned "args.json", is generated by the command "python data_processing/gen_data_gt.py --pth_out /your output path/"

**Comment by admiral-chen** [comment]
Dear all, 

The problem is resolved. Thank you very much :-)

YF

**Comment by Bongnah** [comment]
Then, I wonder how to solve this problem... I met this problem..
